name: Build Release

on:
    workflow_dispatch:

jobs:
    build:
        name: Build Snow Release APK
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v4
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: 21
                  cache: gradle
            - name: Write sign info
              run: |
                  if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
                      echo storePassword='${{ secrets.SIGNING_STORE_PASSWORD }}' >> keystore.properties
                      echo keyAlias='${{ secrets.SIGNING_KEY_ALIAS }}' >> keystore.properties
                      echo keyPassword='${{ secrets.SIGNING_KEY_PASSWORD }}' >> keystore.properties
                      echo storeFile='${{ github.workspace }}/key.jks' >> keystore.properties
                      echo ${{ secrets.KEYSTORE }} | base64 --decode > ${{ github.workspace }}/key.jks
                    fi
            - name: Get Gradle
              run: gradle wrapper
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build Release apk
              run: ./gradlew assembleRelease --stacktrace
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: snow.apk
                  path: app/build/outputs/apk/release/*.apk
